#!/bin/bash

# Define the bucket name
# bucket_name="your-bucket-name"

aws s3api list-buckets --query "Buckets[].Name"

for bucket in $(aws s3api list-buckets --query "Buckets[].Name" --output text)
do
  tags=$(aws s3api get-bucket-tagging --bucket $bucket_name --query "TagSet[?Key=='Department' && Value=='Marketing']")
  if [ ! -z "$tags" ]; then
    echo "Bucket with Department=Marketing: $bucket"
  fi
done



# Create a bucket policy JSON content
bucket_policy=$(cat <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "PublicReadGetObject",
      "Effect": "Allow",
      "Principal": "*",
      "Action": "s3:GetObject",
      "Resource": "arn:aws:s3:::$bucket_name/*"
    }
  ]
}
EOF
)

# Apply the bucket policy
aws s3api put-bucket-policy --bucket "$bucket_name" --policy "$bucket_policy"

# Update public access settings
aws s3api put-public-access-block --bucket "$bucket_name" --public-access-block-configuration BlockPublicAcls=false,IgnorePublicAcls=false,BlockPublicPolicy=false,RestrictPublicBuckets=false

echo "Bucket $bucket_name is now public."
